### ISSUE TITLE
tilix crashed with SIGSEGV

### ISSUE THREAD

**Issue by Jellyfrog** [gnunn1/tilix#1104]
Think I pressed the "view session sidebar"-button and it hanged for a long time and then crashed.
I can upload the coredump somewhere if you need it

```
$ tilix -v
Versions
	Tilix version: 1.6.4
	VTE version: 0.44
	GTK Version: 3.22.11

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
``` 

```
Segfault happened at: 0x562bbbe5654e:	mov    (%rbx),%rax
PC (0x562bbbe5654e) ok
source "(%rbx)" (0x00000000) not located in a known VMA region (needed readable region)!
destination "%rax" ok


=> 0x562bbbe5654e:	mov    (%rbx),%rax
   0x562bbbe56551:	callq  *0xe0(%rax)
   0x562bbbe56557:	mov    %eax,%esi
   0x562bbbe56559:	lea    0x32e740(%rip),%rdi        # 0x562bbc184ca0
   0x562bbbe56560:	callq  0x562bbbe2b5e0
   0x562bbbe56565:	mov    %rax,%r15
   0x562bbbe56568:	mov    %rdx,(%rsp)
   0x562bbbe5656c:	test   %r15,%r15
   0x562bbbe5656f:	je     0x562bbbe5667e
   0x562bbbe56575:	mov    $0x1,%r13d
   0x562bbbe5657b:	mov    0x324746(%rip),%r12        # 0x562bbc17acc8
   0x562bbbe56582:	data16 data16 data16 data16 nopw %cs:0x0(%rax,%rax,1)
   0x562bbbe56590:	mov    (%rbx),%rax
   0x562bbbe56593:	mov    %rbx,%rdi
   0x562bbbe56596:	callq  *0x38(%rax)
   0x562bbbe56599:	mov    %rax,%rbp
```

```
.
Thread 6 (Thread 0x7fc9abe1a700 (LWP 8676)):
#0  0x00007fca107199f9 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fca0f20915a in g_cond_wait_until () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fca0f1978d9 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fca0f1eb936 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fca0f1eaf65 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fca0fab56da in start_thread (arg=0x7fc9abe1a700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7fc9abe1a700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140504148846336, -1062329602742196485, 140728242483182, 140728242483183, 140504148847040, 140504148846336, 1068073402640328443, 1068979892811556603}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007fca1071fd7f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
.
Thread 5 (Thread 0x7fc9d65ff700 (LWP 8677)):
#0  0x00007fca107199f9 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fca0f20915a in g_cond_wait_until () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fca0f1978d9 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fca0f1eb936 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fca0f1eaf65 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fca0fab56da in start_thread (arg=0x7fc9d65ff700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7fc9d65ff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140504861767424, -1062329602742196485, 140728242483294, 140728242483295, 140504861768128, 140504861767424, 1068044040633280251, 1068979892811556603}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007fca1071fd7f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
.
Thread 4 (Thread 0x7fca02c8f700 (LWP 9447)):
#0  0x00007fca10713d8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fca0f1c3576 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fca0f1c368c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fca0f1c36d1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fca0f1eaf65 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fca0fab56da in start_thread (arg=0x7fca02c8f700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7fca02c8f700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140505606846208, -1062329602742196485, 140728242495646, 140728242495647, 140505606846912, 140505606846208, 1069003802615179003, 1068979892811556603}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007fca1071fd7f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
.
Thread 3 (Thread 0x7fca0248e700 (LWP 9448)):
#0  0x00007fca10713d8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fca0f1c3576 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fca0f1c3902 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fca0a5a1476 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007fca0f1eaf65 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fca0fab56da in start_thread (arg=0x7fca0248e700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7fca0248e700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140505598453504, -1062329602742196485, 140728242495998, 140728242495999, 140505598454208, 140505598453504, 1069002702566680315, 1068979892811556603}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007fca1071fd7f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
.
Thread 2 (Thread 0x7fca038fe700 (LWP 9445)):
#0  0x00007fca10713d8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fca0f1c3576 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fca0f1c368c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fca0390646d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007fca0f1eaf65 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fca0fab56da in start_thread (arg=0x7fca038fe700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7fca038fe700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140505619883776, -1062329602742196485, 140728242496222, 140728242496223, 140505619884480, 140505619883776, 1069006525087573755, 1068979892811556603}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#6  0x00007fca1071fd7f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
.
Thread 1 (Thread 0x7fca130e3840 (LWP 9440)):
#0  0x0000562bbbe5654e in  ()
#1  0x0000562bbbe56486 in  ()
#2  0x00007fca1250339a in gtk.Widget.Widget.callBackButtonPressEventGeneric(gtkc.gtktypes.GtkWidget*, gtkc.gdktypes.GdkEvent*, gtk.Widget.Widget.OnButtonPressEventGenericDelegateWrapper) () at /usr/lib/x86_64-linux-gnu/libgtkd-3.so.0
#3  0x00007fca06badf2c in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007fca0e899c25 in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007fca0e8abc32 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007fca0e8b432f in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007fca0e8b4c6f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007fca06cfb24c in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007fca06baafae in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007fca06bad06e in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007fca0cc81c75 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#12 0x00007fca0ccb2d02 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#13 0x00007fca0f1c3377 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007fca0f1c35e0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007fca0f1c368c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007fca06bac2b1 in gtk_main_iteration_do () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007fca1258d11d in gtk.Main.Main.iterationDo(bool) () at /usr/lib/x86_64-linux-gnu/libgtkd-3.so.0
#18 0x0000562bbbe58b1a in  ()
#19 0x0000562bbbe57d3d in  ()
#20 0x0000562bbbe57766 in  ()
#21 0x0000562bbbea398a in  ()
#22 0x00007fca0e899c25 in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007fca0e8abc32 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007fca0e8b488c in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007fca0e8b4c6f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007fca0a57d4b5 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#27 0x00007fca06a7539e in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007fca06a753d4 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007fca06a753d4 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007fca06a753d4 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007fca06aa8fe3 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x00007fca0e899c25 in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007fca0e8abd03 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007fca0e8b488c in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007fca0e8b4c6f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007fca06aab09d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#37 0x00007fca06aab105 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#38 0x00007fca0e899c25 in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#39 0x00007fca0e8ab60c in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#40 0x00007fca0e8b488c in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#41 0x00007fca0e8b4c6f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#42 0x00007fca06aa9500 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#43 0x00007fca0e687e18 in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#44 0x00007fca0e68787a in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#45 0x00007fca0e89a93a in g_cclosure_marshal_generic_va () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#46 0x00007fca0e899e54 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#47 0x00007fca0e8b457d in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#48 0x00007fca0e8b4c6f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#49 0x00007fca06b64e41 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#50 0x00007fca0e89c9d7 in g_cclosure_marshal_VOID__BOXEDv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#51 0x00007fca0e899e54 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#52 0x00007fca0e8b457d in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#53 0x00007fca0e8b4c6f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#54 0x00007fca06b6210e in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#55 0x00007fca06b6373b in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#56 0x00007fca06b663bd in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#57 0x00007fca06b3393e in gtk_event_controller_handle_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#58 0x00007fca06cf8fab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#59 0x00007fca06bae021 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#60 0x00007fca0e899e54 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#61 0x00007fca0e8b4051 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#62 0x00007fca0e8b4c6f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#63 0x00007fca06cfb24c in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#64 0x00007fca06baafae in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#65 0x00007fca06bad06e in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#66 0x00007fca0cc81c75 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#67 0x00007fca0ccb2d02 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#68 0x00007fca0f1c3377 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#69 0x00007fca0f1c35e0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#70 0x00007fca0f1c368c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#71 0x00007fca0a5754dd in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#72 0x0000562bbbeb1aad in  ()
#73 0x00007fca10c88a0f in rt.dmain2._d_run_main(int, char**, extern(C) int(char[][]) function).runAll().__lambda1() () at /usr/lib/x86_64-linux-gnu/libdruntime-ldc.so.71
#74 0x00007fca10c88954 in rt.dmain2._d_run_main(int, char**, extern(C) int(char[][]) function).tryExec(scope void() delegate) () at /usr/lib/x86_64-linux-gnu/libdruntime-ldc.so.71
#75 0x00007fca10c8887d in _d_run_main () at /usr/lib/x86_64-linux-gnu/libdruntime-ldc.so.71
#76 0x00007fca106373f1 in __libc_start_main (main=0x562bbbedfb70, argc=2, argv=0x7ffdd8e77838, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdd8e77828) at ../csu/libc-start.c:291
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 6707741114468361979, 94745835783296, 140728242501680, 0, 0, 1061276197841495803, 1069033286610282235}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7ffdd8e77850, 0x7fca13118168}, data = {prev = 0x0, cleanup = 0x0, canceltype = -655919024}}}
        not_first_call = <optimized out>
#77 0x0000562bbbe2c4aa in  ()
```

**Comment by gnunn1** [comment]
Is this reproduceable?

**Comment by Jellyfrog** [comment]
Only happened once so far

**Comment by gnunn1** [comment]
OK, I'm going to close this, sometimes stuff happens. If it happens again feel free to re-open it.
