### ISSUE TITLE
Tilix crashes since 1.7.1

### ISSUE THREAD

**Issue by Salamandar** [gnunn1/tilix#1197]
I don't really know how to debug this, but Tilix sometimes crashes while doing nothing, even when tilix windows are not in focus. It happens 2/3 times a day at work and at home…
Started with xterm :
```
***MEMORY-ERROR***: tilix[26023]: GSlice: assertion failed: sinfo->n_allocated > 0
[1]    26023 abort (core dumped)  tilix
```

**Comment by gnunn1** [comment]
If you are able to, compiling tilix manually with debug info and getting a back trace with gdb would be hugely helpful. You would need to install ldc2 (the D compiler) and dub on your system and then run the following commands in a different terminal (i.e. gnome terminal) and make sure no other instance of tilix is running:

```
cd /tmp
git clone https://github.com/gnunn1/tilix
dub build --build=debug
gdb ./tilix
```
This will start gdb, in the gdb console type ```run``` to start tilix. When it crashes, go back to the gdb console and type ```bt``. Paste the results of that here.

**Comment by gnunn1** [comment]
Oops, forgot about those. Thanks for having a look at this, always annoying dealing with issues you can't reproduce.

**Comment by Salamandar** [comment]
Oh, that's too bad, it seems it's inside libgtk… without debug symbols :/
```
#0  0x00007ffff6b888a0 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff6b89f09 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff443168b in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff44316f4 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff43f53e6 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff4431d90 in g_slice_free1 () at /usr/lib/libglib-2.0.so.0
#6  0x00007fffef9c55c6 in  () at /usr/lib/libgtk-3.so.0
#7  0x00007ffff2dd0645 in g_object_unref () at /usr/lib/libgobject-2.0.so.0
#8  0x00007fffef9b3fce in  () at /usr/lib/libgtk-3.so.0
#9  0x00007ffff4425122 in  () at /usr/lib/libglib-2.0.so.0
#10 0x00007ffff442527f in g_hash_table_unref () at /usr/lib/libglib-2.0.so.0
#11 0x00007fffef9b3fdd in  () at /usr/lib/libgtk-3.so.0
#12 0x00007fffef9b1d4d in  () at /usr/lib/libgtk-3.so.0
#13 0x00007fffef9b2b45 in  () at /usr/lib/libgtk-3.so.0
#14 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#15 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#16 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#17 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#18 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#19 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#20 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#21 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#22 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#23 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#24 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#25 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#26 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#27 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#28 0x00007fffef9b2b5b in  () at /usr/lib/libgtk-3.so.0
#29 0x00007fffef998f28 in  () at /usr/lib/libgtk-3.so.0
#30 0x00007ffff2dd26f5 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#31 0x00007ffff2de60b0 in  () at /usr/lib/libgobject-2.0.so.0
#32 0x00007ffff2dea696 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#33 0x00007ffff2deb920 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#34 0x00007ffff3c7d23f in  () at /usr/lib/libgdk-3.so.0
#35 0x00007ffff3c67ac3 in  () at /usr/lib/libgdk-3.so.0
#36 0x00007ffff443ecb3 in  () at /usr/lib/libglib-2.0.so.0
#37 0x00007ffff44400be in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#38 0x00007ffff4441f69 in  () at /usr/lib/libglib-2.0.so.0
#39 0x00007ffff4441fae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#40 0x00007ffff30535ae in g_application_run () at /usr/lib/libgio-2.0.so.0
#41 0x000055555603cfcc in gio.Application.Application.run(immutable(char)[][]) (this=0x7ffff7edd800, argv=...) at ../../.dub/packages/gtk-d-3.7.1/gtk-d/generated/gtkd/gio/Application.d:931
#42 0x0000555555eccb6d in D main (args=...) at source/app.d:146
```

**Comment by Salamandar** [comment]
> Oops, forgot about those. Thanks for having a look at this, always annoying dealing with issues you can't reproduce.
That's what I live everyday, so just trying to make a fellow dev's life easier x)

**Comment by gnunn1** [comment]
One other thing to try, can you modify the GtkD dependency in ```dub.json`` and ```dub.selections.json``` to use version 3.6.5 instead of 3.7.1 and see if it makes any difference.

**Comment by gnunn1** [comment]
Can you please try compiling the latest from master, I made a fix dfor #1192 which will hopefully address this as well.

**Comment by Salamandar** [comment]
@gnunn1 I rebuilt Tilix this morning, didn't crash for now :) I'll tell you if that happens again, but it may be closed for now.

**Comment by gnunn1** [comment]
Thanks, if you run into the same issue please re-open.

**Comment by Salamandar** [comment]
I just had a crash while ctrl-maj-F. But maybe that's unrelated. Unfortunately tilix was run headless.

**Comment by Salamandar** [comment]
I can safely say that the issue is fixed with all those gtkd updates. Yay :)
