### ISSUE TITLE
ramdom SIGSEGV

### ISSUE THREAD

**Issue by bestouff** [gnunn1/tilix#1230]
Hi,

Tilix randomly crashes, about once a week on me. I typically have 2 windows with lots of subwindows opened. Debian sarge, GNOME.
At first the official debian package was crashing (see [#883676](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883676)), now I've tried the github release and still have crashes:
```gdb
Thread 1 "tilix" received signal SIGSEGV, Segmentation fault.
0x0000555555838378 in ?? ()
(gdb) bt
#0  0x0000555555838378 in  ()
#1  0x00007ffff6093853 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6092dd5 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff60931a0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff609322c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff4f0dbed in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00005555559c802d in  ()
#7  0x00005555559117d6 in  ()
#8  0x0000555555e6fdcf in  ()
#9  0x0000555555e6fd14 in  ()
#10 0x0000555555e6fc40 in  ()
#11 0x0000555555981dd5 in  ()
#12 0x00007ffff6bc3561 in __libc_start_main (main=
    0x555555981db0, argc=1, argv=0x7fffffffe6a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe698)
    at ../csu/libc-start.c:297
#13 0x0000555555809c2a in  ()
```

**Comment by gnunn1** [comment]
We fixed a few issues in 1.7.3 which I just released a couple of days ago, is that the release you were trying from github?

**Comment by bestouff** [comment]
Nope, I tried the previous one. I'll try 1.7.3.

**Comment by gnunn1** [comment]
Thanks, I'm going to close this but please re-open if you can reproduce in 1.7.3

**Comment by bestouff** [comment]
I confirm I can't reproduce in 1.7.5. Thanks !
