### ISSUE TITLE
Crash: free(): invalid pointer

### ISSUE THREAD

**Issue by csillag** [gnunn1/tilix#1298]
I am having random crashed with this message:

> free(): invalid pointer
> Terminated

My versions are:

> Versions
> 	Tilix version: 1.7.5
> 	VTE version: 0.50
> 	GTK Version: 3.22.11
> 
> Tilix Special Features
> 	Notifications enabled=0
> 	Triggers enabled=0
> 	Badges enabled=0

This makes tilix completely unusable for me...

**Comment by csillag** [comment]
I am on Debian. (stable/testing/unstable hybrid). Desktop environment is Cinnamon.

I have now rebuilt tilix together with debug symbols, and running it via gdb. I will post the backtrace when I get the next crash.

**Comment by gnunn1** [comment]
Any chance you have the same issue as #1275?

**Comment by csillag** [comment]
Here is  backtrace:

```
Thread 1 "tilix" received signal SIGSEGV, Segmentation fault.
0x00007ffff291e453 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff291e453 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff291e986 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff291fb3e in g_slice_free1 () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#33 0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#36 0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#42 0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#45 0x00007ffff28ef7aa in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#46 0x00007ffff28f00df in g_hash_table_unref () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007ffff43ee31b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#48 0x00007ffff43ec122 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#49 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#50 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#51 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#52 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#53 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#54 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#55 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#56 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#57 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#58 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#59 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#60 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#61 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#62 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#63 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#64 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#65 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#66 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#67 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#68 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#69 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#70 0x00007ffff43ec0e6 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#71 0x00007ffff43ec326 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#72 0x00007ffff454a801 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#73 0x00007ffff45f7715 in gtk_widget_style_get_valist () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#74 0x00007ffff45f7ab4 in gtk_widget_style_get () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#75 0x00007ffff440bfef in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#76 0x00007ffff440c0db in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#77 0x00007ffff2bdd5fe in g_cclosure_marshal_VOID__FLAGSv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#78 0x00007ffff2bdb1a4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#79 0x00007ffff2bf58cd in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#80 0x00007ffff2bf5fbf in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#81 0x00007ffff45f805c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#82 0x00007ffff438a217 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#83 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#84 0x00007ffff438a217 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#85 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#86 0x00007ffff444d0e0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#87 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#88 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#89 0x00007ffff438a217 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#90 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#91 0x00007ffff438a217 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#92 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#93 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#94 0x00007ffff438a217 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#95 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#96 0x00007ffff44d7be2 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#97 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#98 0x00007ffff438a217 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#99 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#100 0x00007ffff44d7be2 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#101 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#102 0x00007ffff438a217 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#103 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#104 0x00007ffff44d7be2 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#105 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#106 0x00007ffff438a217 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#107 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#108 0x00007ffff44d7be2 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#109 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#110 0x00007ffff438a217 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#111 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#112 0x00007ffff438a217 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#113 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#114 0x00007ffff4541870 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#115 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#116 0x00007ffff44c4f6e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#117 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#118 0x00007ffff44d1930 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#119 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#120 0x00007ffff45fcad9 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#121 0x00007ffff45f81b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#122 0x00007ffff45f8a9e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#123 0x00007ffff45fd241 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#124 0x00007ffff449aaac in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#125 0x00007ffff2bdaf75 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#126 0x00007ffff2bed37d in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#127 0x00007ffff2bf567f in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#128 0x00007ffff2bf5fbf in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#129 0x00007ffff45e757c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#130 0x00007ffff4499ad4 in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#131 0x00007ffff3faae15 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#132 0x00007ffff3fdbea2 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#133 0x00007ffff29017f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#134 0x00007ffff2901a60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#135 0x00007ffff2901b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#136 0x00007ffff2ebd72d in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#137 0x000055555579ac5b in D main (args=...) at /root/tilix-1.7.5/source/app.d:146

```

**Comment by gnunn1** [comment]
How did you build tilix, with autotools or dub? If autotools please use dub instead:

```dub build --build=debug -config=trace```


 Can you confirm you are using the latest version of gtkd which is 3.7.5 and not 3.7.3 which is what shipped with Debian. Did you look at that issue I linked to previously, your problem sounds exactly the same as that.

**Comment by csillag** [comment]
I built tilix with the official Debian packaging scripts, with the official
Debian packages as dependencies.

2018. febr. 18. du. 2:07 ezt írta ("Gerald Nunn" <notifications@github.com
>):

How did you build tilix, with autotools or dub? If autotools please use dub
instead:

dub build --build=debug -config=trace

Can you confirm you are using the latest version of gtkd which is 3.7.5 and
not 3.7.3 which is what shipped with Debian. Did you look at that issue I
linked to previously, your problem sounds exactly the same as that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gnunn1/tilix/issues/1298#issuecomment-366514931>, or mute
the thread

**Comment by csillag** [comment]
I did look at the linked issue, but it is not clear to me whether or not it
is the same.

2018. febr. 18. du. 2:07 ezt írta ("Gerald Nunn" <notifications@github.com

**Comment by gnunn1** [comment]
I believe it is the same, please clone the tilix repo and build it using dub as per above and I expect the problem will be solved.

**Comment by gnunn1** [comment]
I should be clearer, it's the same in that GtkD 3.7.3 had memory issues and this can manifest itself in different ways including what you are seeing.

**Comment by csillag** [comment]
>  GtkD 3.7.3 had memory issues

**Comment by csillag** [comment]
> GtkD 3.7.3 had memory issues

Debian has GtkD 3.7.1 ...

**Comment by csillag** [comment]
> GtkD 3.7.3 had memory issues

Well, then which is the recommended version? According to [the homepage](https://gtkd.org):

> Latest Release: 3.7.3 (2017-12-16)

**Comment by gnunn1** [comment]
Me bad, it's 3.7.3 the latest, just remembered Debian had old version.

**Comment by aleho** [comment]
The Debian bug [1] got closed, so unstable should have latest libs in a few hours.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=889652

**Comment by csillag** [comment]
Indeed, the newest version is now in Debian.

However, I just had a new crash yesterday.
I will now re-build it again, with the debug symbols, and get you a new trace...

**Comment by gnunn1** [comment]
Can you confirm if this is fixed with the latest version of GtkD on debian?

**Comment by csillag** [comment]
On the contrary. I can confirm that this is *not* fixed.

**Comment by gnunn1** [comment]
Ok, when you re-build it please use ```dub``` rather then debian packaging as I'm quite interested whether it's something in the code versus something specific to the way debian builds it.

**Comment by gnunn1** [comment]
@csillag Are you still looking at this? I haven't seen any other reports of this issue and I still feel like it was tied to the Debian GtkD version.

**Comment by csillag** [comment]
I haven't seen it for a while, so let's close it down. If it reappears, I will ping back.
Thank you for the attention anyway.
