### ISSUE TITLE
Segfault when double-clicking on separator

### ISSUE THREAD

**Issue by michaudg** [gnunn1/tilix#1373]
When double-clicking on the separator to set equal height or width for tiles, Tilix crashes with segfault.

ArchLinux
Tilix version: 1.7.8-0.0.1
VTE version: 0.52
GTK Version: 3.22.29

**Comment by dsboger** [comment]
Looks like a pre-release made into Arch repos. Disregarding that, though, I can reproduce the issue on my end too.

**Comment by phw** [comment]
Only a single commit https://github.com/gnunn1/tilix/commit/76ac251da7f6e639a1a49d1c4d4ad48e135ab79f in the Arch package is from development version, the rest is the 1.7.7 release (see also discussion in #1356). Not sure if this commit can be responsible for the crash.

@Vild @gnunn1 Any ideas?

**Comment by dsboger** [comment]
@phw You are right. It so happens the same commit also bumps the version number.

I've tried to capture a backtrace with gdb and got the following (that's the output after the double click):

```
Thread 1 "tilix" received signal SIGSEGV, Segmentation fault.
0x000055555573569f in _D7gobject7ObjectGQi__T6opCastTC3gtk9ContainerQkZQBaMFZQy ()
(gdb) bt
#0  0x000055555573569f in _D7gobject7ObjectGQi__T6opCastTC3gtk9ContainerQkZQBaMFZQy ()
#1  0x000055555573564d in _D2gx5tilix7session7Session17redistributePanesMFC3gtk5PanedQgZ12getRootPanedMFZQBf ()
#2  0x0000555555735098 in _D2gx5tilix7session7Session17redistributePanesMFC3gtk5PanedQgZv ()
#3  0x0000555555735017 in _D2gx5tilix7session7Session11createPanedMFE3gtk1c5types14GtkOrientationZ12__dgliteral2MFC3gdk5EventQgCQCh6WidgetQhZb ()
#4  0x00007ffff7579652 in _D7gobject8DClosureQj__T17d_closure_marshalTDFC3gdk5EventQgC3gtk6WidgetQhZbZQCaUPSQDc1c5types8GClosurePSQDyQwQw6GValuekQrPvQcZv ()
    at /usr/lib/libgtkd-3.so.0
#5  0x00007ffff45e9a4d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff45fce40 in  () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff4605081 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff4606130 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#9  0x00007fffedcadad5 in  () at /usr/lib/libgtk-3.so.0
#10 0x00007fffedb5ab3b in  () at /usr/lib/libgtk-3.so.0
#11 0x00007fffedb5ccf3 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#12 0x00007ffff2b07526 in  () at /usr/lib/libgdk-3.so.0
#13 0x00007ffff2b38e45 in  () at /usr/lib/libgdk-3.so.0
#14 0x00007ffff430f368 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#15 0x00007ffff430f5b1 in  () at /usr/lib/libglib-2.0.so.0
#16 0x00007ffff430f63e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#17 0x00007ffff3b4a97e in g_application_run () at /usr/lib/libgio-2.0.so.0
#18 0x00005555557b906a in D main ()
```

**Comment by gnunn1** [comment]
I can reproduce this and get the line numbers, not sure what the issue is since this code hasn't changed in quite a while. I'll have a look in more detail.

```
Thread 1 "tilix" received signal SIGSEGV, Segmentation fault.
0x0000555555cd6637 in _D7gobject7ObjectGQi__T6opCastTC3gtk9ContainerQkZQBaMFZQy (this=0x0)
    at ../../../.dub/packages/gtk-d-3.8.0/gtk-d/generated/gtkd/gobject/ObjectG.d:173
173				if ( !g_type_is_a(gObject.gTypeInstance.gClass.gType, T.getType()) )
(gdb) bt
#0  0x0000555555cd6637 in _D7gobject7ObjectGQi__T6opCastTC3gtk9ContainerQkZQBaMFZQy (this=0x0)
    at ../../../.dub/packages/gtk-d-3.8.0/gtk-d/generated/gtkd/gobject/ObjectG.d:173
#1  0x0000555555dc9133 in _D2gx5tilix7session7Session17redistributePanesMFC3gtk5PanedQgZ12getRootPanedMFZQBf (this=0x7fffffffd7d0) at source/gx/tilix/session.d:235
#2  0x0000555555dc8ed0 in _D2gx5tilix7session7Session17redistributePanesMFC3gtk5PanedQgZv (this=0x7ffff7ebc000, paned=0x7ffff7ee6c80) at source/gx/tilix/session.d:240
#3  0x0000555555dc8e9d in _D2gx5tilix7session7Session11createPanedMFE3gtk1c5types14GtkOrientationZ12__dgliteral2MFC3gdk5EventQgCQCh6WidgetQhZb (this=0x7ffff7ee8de0, w=0x7ffff7ee6c80, event=0x7ffff7f00360) at source/gx/tilix/session.d:201
#4  0x000055555601ff12 in _D7gobject8DClosureQj__T17d_closure_marshalTDFC3gdk5EventQgC3gtk6WidgetQhZbZQCaUPSQDc1c5types8GClosurePSQDyQwQw6GValuekQrPvQcZv (closure=0x555556e05650, return_value=0x7fffffffda30, n_param_values=2, param_values=0x7ffff7effc00, invocation_hint=0x7fffffffda10, marshal_data=0x0)
    at ../../../.dub/packages/gtk-d-3.8.0/gtk-d/generated/gtkd/gobject/DClosure.d-mixin-138:140
#5  0x00007ffff2435a4d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff2448e40 in  () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff2451081 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff2452130 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#9  0x00007fffef212ad5 in  () at /usr/lib/libgtk-3.so.0
#10 0x00007fffef0bfb3b in  () at /usr/lib/libgtk-3.so.0
#11 0x00007fffef0c1cf3 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
```

**Comment by f2404** [comment]
@gnunn1 Could this be not because of the code change, but because of gtkd version change?
```
         "gtk-d:gtkd": {
-            "version": "3.7.5"
+            "version": "3.8.0"
         },
         "gtk-d:vte": {
-            "version": "3.7.5"
+            "version": "3.8.0"
         }
```

**Comment by gnunn1** [comment]
@f2404 Yes it is possible if the problem is in GtkD and this code has changed between versions. I have not had a chance to look in detail at this point.

**Comment by gnunn1** [comment]
I suspect this is a GtkD bug but for now I have added a check that should fix it. A corresponding issue has been opened in the GtkD project,
