### ISSUE TITLE
Crashing when moving the cursor from one display to another

### ISSUE THREAD

**Issue by spavezv** [gnunn1/tilix#1453]
I am using wayland and had set up different scale for two monitors:

- Fedora release 28 (Twenty Eight)
- GNOME Shell 3.28.2

Main display

- Resolution: 3840 x 2169
- Scale: 200%

Secondary display

- Resolution: 1920 x 1200
- Scale: 100%

Here is the full back trace of the error:

```bash
(gdb) bt full
#0  0x00007ffff52b1f2b in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 22728544, 1, 140737307500054, 4222451712, 22728544, 22728544, 140737306639688, 22728544, 128, 4, 140737488339936, 0, 140737258852592, 0, 140737258852908}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007ffff529c561 in __GI_abort () at abort.c:79
        save_stage = 1
        act = 
          {__sigaction_handler = {sa_handler = 0x7ffff251f800 <g_log_default_handler>, sa_sigaction = 0x7ffff251f800 <g_log_default_handler>}, sa_mask = {__val = {0, 140737285343790, 140737285343790, 9516992, 47244640258, 0, 0, 0, 140737488340200, 21474836480, 140737488340048, 140737308011504, 8789522619432716032, 0, 9813696, 0}}, sa_flags = 9645600, sa_restorer = 0x7fffffffc6a0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff0ef12d5 in wl_abort (fmt=fmt@entry=0x7ffff0ef153f "Error sending request: %s\n") at src/wayland-util.c:417
        argp = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffc600, reg_save_area = 0x7fffffffc540}}
#3  0x00007ffff0eed00d in wl_proxy_marshal_array_constructor_versioned (proxy=proxy@entry=0x95bec0, opcode=opcode@entry=0, args=args@entry=0x7fffffffc6a0, interface=interface@entry=0x0, version=5) at src/wayland-client.c:754
        closure = 0x932e20
        new_proxy = 0x0
        message = 0x7ffff10f3ea0 <wl_pointer_requests>
#4  0x00007ffff0eed06d in wl_proxy_marshal_array_constructor (proxy=proxy@entry=0x95bec0, opcode=opcode@entry=0, args=args@entry=0x7fffffffc6a0, interface=interface@entry=0x0)
    at src/wayland-client.c:694
#5  0x00007ffff0eed160 in wl_proxy_marshal (proxy=0x95bec0, opcode=opcode@entry=0) at src/wayland-client.c:791
        args = 
            {{i = 6688, u = 6688, f = 6688, s = 0x1a20 <error: Cannot access memory at address 0x1a20>, o = 0x1a20, n = 6688, a = 0x1a20, h = 6688}, {i = 10036448, u = 10036448, f = 10036448, s = 0x9924e0 "\300?\017\361\377\177", o = 0x9924e0, n = 10036448, a = 0x9924e0, h = 10036448}, {i = 19, u = 19, f = 19, s = 0x13 <error: Cannot access memory at address 0x13>, o = 0x13, n = 19, a = 0x13, h = 19}, {i = 19, u = 19, f = 19, s = 0x13 <error: Cannot access memory at address 0x13>, o = 0x13, n = 19, a = 0x13, h = 19}, {i = 15316160, u = 15316160, f = 15316160, s = 0xe9b4c0 "\340\032\224", o = 0xe9b4c0, n = 15316160, a = 0xe9b4c0, h = 15316160}, {i = -226521497, u = 4068445799, f = -226521497, s = 0x7ffff27f8e67 <g_object_unref+103> "\215U\377\211\301\211\350\360A\017\261\024$u\340H\213\003\220\203\375\002u\005\203\341\001uT[]A\\A]A^\303\017\037", o = 0x7ffff27f8e67 <g_object_unref+103>, n = 4068445799, a = 0x7ffff27f8e67 <g_object_unref+103>, h = -226521497}, {i = 1, u = 1, f = 1, s = 0x1 <error: Cannot access memory at address 0x1>, o = 0x1, n = 1, a = 0x1, h = 1}, {i = 47, u = 47, f = 47, s = 0x2f <error: Cannot access memory at address 0x2f>, o = 0x2f, n = 47, a = 0x2f, h = 47}, {i = 1, u = 1, f = 1, s = 0x1 <error: Cannot access memory at address 0x1>, o = 0x1, n = 1, a = 0x1, h = 1}, {i = -229415108, u = 4065552188, f = -229415108, s = 0x7ffff253673c <g_slice_free1+156> "I\211\307H\205\300\017\204\250\001", o = 0x7ffff253673c <g_slice_free1+156>, n = 4065552188, a = 0x7ffff253673c <g_slice_free1+156>, h = -229415108}, {i = 10081088, u = 10081088, f = 10081088, s = 0x99d340 "@\035\230", o = 0x99d340, n = 10081088, a = 0x99d340, h = 10081088}, {i = -203407008, u = 4091560288, f = -203407008, s = 0x7ffff3e04160 <_gdk_frame_clock_freeze+48> "\205\300t\034H\213\205\250", o = 0x7ffff3e04160 <_gdk_frame_clock_freeze+48>, n = 4091560288, a = 0x7ffff3e04160 <_gdk_frame_clock_freeze+48>, h = -203407008}, {i = 10081088, u = 10081088, f = 10081088, s = 0x99d340 "@\035\230", o = 0x99d340, n = 10081088, a = 0x99d340, h = 10081088}, {i = -203406790, u = 4091560506, f = -203406790, s = 0x7ffff3e0423a <gdk_frame_clock_get_frame_counter+42> "\205\300t\022H\213C\030[H\213", o = 0x7ffff3e0423a <gdk_frame_clock_get_frame_counter+42>, n = 4091560506, a = 0x7ffff3e0423a <gdk_frame_clock_get_frame_counter+42>, h = -203406790}, {i = 9736288, u = 9736288, f = 9736288, s = 0x949060 "0I\224", o = 0x949060, n = 9736288, a = 0x949060, h = 9736288}, {i = -203026845, u = 4091940451, f = -203026845, s = 0x7ffff3e60e63 <on_frame_clock_after_paint+179> "\213\065\003\237%", o = 0x7ffff3e60e63 <on_frame_clock_after_paint+179>, n = 4091940451, a = 0x7ffff3e60e63 <on_frame_clock_after_paint+179>, h = -203026845}, {i = 0, u = 0, f = 0, s = 0x0, o = 0x0, n = 0, a = 0x0, h = 0}, {i = 16285984, u = 16285984, f = 16285984, s = 0xf88120 "\001", o = 0xf88120, n = 16285984, a = 0xf88120, h = 16285984}, {i = 1, u = 1, f = 1, s = 0x1 <error: Cannot access memory at address 0x1>, o = 0x1, n = 1, a = 0x1, h = 1}, {i = -14064, u = 4294953232, f = -14064, s = 0x7fffffffc910 "\001", o = 0x7fffffffc910, n = 4294953232, a = 0x7fffffffc910, h = -14064}}
        ap = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fffffffc820, reg_save_area = 0x7fffffffc750}}
#6  0x00007ffff3e4c9a3 in wl_pointer_set_cursor (hotspot_y=<optimized out>, hotspot_x=<optimized out>, surface=<optimized out>, serial=<optimized out>, wl_pointer=<optimized out>)
    at ../../gdk/wayland/tablet-unstable-v2-client-protocol.h:1205
        seat = 0x960040 [GdkWaylandSeat]
        pointer = 0x960120
        buffer = 0xa25590
        x = 19
        y = 19
        w = 40
        h = 40
---Type <return> to continue, or q <return> to quit---
        scale = 1
        next_image_index = <optimized out>
        next_image_delay = 0
        retval = 0
        tablet = <optimized out>
#7  0x00007ffff3e4c9a3 in gdk_wayland_device_update_window_cursor (device=0x9990c0 [GdkWaylandDevice]) at gdkdevice-wayland.c:435
        seat = 0x960040 [GdkWaylandSeat]
        pointer = 0x960120
        buffer = 0xa25590
        x = 19
        y = 19
        w = 40
        h = 40
        scale = 1
        next_image_index = <optimized out>
        next_image_delay = 0
        retval = 0
        tablet = <optimized out>
#8  0x00007fffee32503e in ffi_call_unix64 () at ../src/x86/unix64.S:76
#9  0x00007fffee3249ff in ffi_call (cif=<optimized out>, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>) at ../src/x86/ffi64.c:525
        classes = {X86_64_INTEGER_CLASS, X86_64_NO_CLASS, 4042203004, 32767}
        stack = <optimized out>
        argp = <optimized out>
        arg_types = <optimized out>
        gprcount = <optimized out>
        ssecount = <optimized out>
        ngpr = 1
        nsse = 0
        i = <optimized out>
        avn = <optimized out>
        ret_in_memory = <optimized out>
        reg_args = <optimized out>
#10 0x00007ffff0ef02dd in wl_closure_invoke (closure=closure@entry=0x163c8f0, flags=flags@entry=1, target=<optimized out>, 
    target@entry=0x9924e0, opcode=opcode@entry=1, data=<optimized out>) at src/connection.c:996
        count = <optimized out>
        cif = {abi = FFI_UNIX64, nargs = 3, arg_types = 0x7fffffffc9c0, rtype = 0x7fffee325430 <ffi_type_void>, bytes = 0, flags = 0}
        ffi_types = 
          {0x7fffee325310 <ffi_type_pointer>, 0x7fffee325310 <ffi_type_pointer>, 0x7fffee325310 <ffi_type_pointer>, 0x0, 0xe, 0x8bf070, 0xcf, 0x100, 0xffffffffffffefd0, 0x3, 0x330000000e, 0x0, 0x0, 0x6e0000005b, 0x0, 0x770000007c, 0x7fffffffcc68, 0x7ffff5634c40 <main_arena>, 0xd8, 0xc, 0xffffffffffffefd0, 0x2d}
        ffi_args = 
          {0x7fffffffc990, 0x7fffffffc998, 0x163c908, 0x7ffff10f4790 <wl_buffer_events>, 0x0, 0x79faa840e48c4700, 0x7ffff10f4790 <wl_buffer_events>, 0x7ffff0eef030 <wl_closure_init+224>, 0x93abb0, 0x0, 0x8, 0x93aa60, 0x9867e0, 0x7ffff0eef12d <wl_closure_close_fds+77>, 0xd3016f, 0x79faa840e48c4700, 0xd300e0, 0x163c820, 0x7fffffffcb30, 0x163c820, 0x163c800, 0x7ffff0ef19b5}
        implementation = <optimized out>
#11 0x00007ffff0eeca39 in dispatch_event (display=display@entry=0x93aa60, queue=<optimized out>) at src/wayland-client.c:1434
        closure = 0x163c8f0
        proxy = 0x9924e0
        opcode = 1
        proxy_destroyed = <optimized out>
#12 0x00007ffff0eedf5c in dispatch_queue (queue=0x93ab28, display=0x93aa60) at src/wayland-client.c:1580
---Type <return> to continue, or q <return> to quit---
        count = 124
        ret = <optimized out>
#13 0x00007ffff0eedf5c in wl_display_dispatch_queue_pending (display=0x93aa60, queue=0x93ab28) at src/wayland-client.c:1822
        ret = <optimized out>
#14 0x00007ffff0eedfc0 in wl_display_dispatch_pending (display=<optimized out>) at src/wayland-client.c:1885
#15 0x00007ffff3e57da8 in _gdk_wayland_display_queue_events (display=<optimized out>) at gdkeventsource.c:201
        display_wayland = <optimized out>
        source = 0x95c800
        __func__ = "_gdk_wayland_display_queue_events"
#16 0x00007ffff3df68c4 in gdk_display_get_event (display=display@entry=0x940010 [GdkWaylandDisplay]) at gdkdisplay.c:438
        __func__ = "gdk_display_get_event"
#17 0x00007ffff3e57ab6 in gdk_event_source_dispatch (base=<optimized out>, callback=<optimized out>, data=<optimized out>) at gdkeventsource.c:120
        source = <optimized out>
        display = 0x940010 [GdkWaylandDisplay]
        event = <optimized out>
#18 0x00007ffff25188ad in g_main_dispatch (context=0x94b220) at gmain.c:3177
        dispatch = 0x7ffff3e57aa0 <gdk_event_source_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = 0x0
        cb_data = 0x0
        need_destroy = <optimized out>
        source = 0x95c800
        current = 0x9c6dc0
        i = 0
        __func__ = "g_main_dispatch"
#19 0x00007ffff25188ad in g_main_context_dispatch (context=context@entry=0x94b220) at gmain.c:3830
#20 0x00007ffff2518c78 in g_main_context_iterate (context=context@entry=0x94b220, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3903
        max_priority = 2147483647
        timeout = 429
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 7
        fds = 0x141bf20
#21 0x00007ffff2518d10 in g_main_context_iteration (context=context@entry=0x94b220, may_block=may_block@entry=1) at gmain.c:3964
        retval = <optimized out>
#22 0x00007ffff2adc675 in g_application_run (application=0x99d230 [GtkApplication], argc=<optimized out>, argv=0x7ffff7ef1010) at gapplication.c:2470
        arguments = 0x9c5ca0
        status = 0
        context = 0x94b220
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#23 0x00000000005cf75f in D main (args=...) at /usr/src/debug/tilix-1.8.1-1.fc28.x86_64/source/app.d:146
        de = 0x0
        gtkError = <optimized out>
        result = 0
        tilixApp = 0x7ffff7ee4200
```

This takes a while to happen but every time that I noticed happening is when moving the cursor from the secondary display to the main, where I have full screen tilix.

**Comment by gnunn1** [comment]
I will have a look but this might be challenging to reproduce.

**Comment by spavezv** [comment]
Hi @gnunn1 
Since tilix was giving me issues I used gnome-terminal. The same issue happened with it, so it seems this has to do  with wayland and display scalling. I'm closing this ticket since is not a bug related specifically to tilix.
