### ISSUE TITLE
tilix-nautilus not working on Fedora 29 Beta

### ISSUE THREAD

**Issue by suckybell** [gnunn1/tilix#1547]
I've installed tilix and tilix-nautilus on the Fedora 29 Beta, and the nautilus extension doesn't seem to be working.  Tilix itself works fine, though.  Here's the terminal output when running Nautilus.

```
[louis@louis-thinkpad ~]$ nautilus

(nautilus:27629): Nautilus-Python-WARNING **: 20:12:48.612: g_module_open libpython failed: /usr/lib64/libpython3.7.so.1.0: cannot open shared object file: No such file or directory
ImportError: could not import gobject (error was: ImportError('/usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError'))

(nautilus:27629): Nautilus-Python-WARNING **: 20:12:48.670: pygobject initialization failed

(nautilus:27629): Nautilus-Python-WARNING **: 20:12:48.670: nautilus_python_init_python failed
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/open-tilix.py", line 15, in <module>
    from gi import require_version
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError
```

**Comment by bilelmoussaoui** [comment]
Not a Tilix issue. You should report this upstream instead :)
