### ISSUE TITLE
Nautilus Plugin Error on Silverblue 29

### ISSUE THREAD

**Issue by alex285** [gnunn1/tilix#1563]
The plugin doesn't start (no option on menu)

**Tilix Version**
```
tilix-1.8.3-2.fc29.x86_64
```

**Nautilus Version**
```
nautilus-3.30.2-1.fc29.x86_64
```

**Silverblue Version**
```
State: idle
AutomaticUpdates: check; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree://fedora-workstation:fedora/29/x86_64/silverblue
                   Version: 29.20181024.n.0 (2018-10-24 11:51:33)
                BaseCommit: 6bb68c92d1f22228354939cef904f3977380e11f58d0a67186268c820f434492
              GPGSignature: Valid signature by 5A03B4DD8254ECA02FDA1637A20AA56B429476B4
      ReplacedBasePackages: runc 2:1.0.0-55.dev.git578fe65.fc29 -> 2:1.0.0-56.dev.git78ef28e.fc29
           LayeredPackages: chromium chromium-libs-media-freeworld dconf-editor docker-ce docker-compose ffmpeg file-roller gnome-tweaks gparted
                            gstreamer1-libav pantheon-desktop tilix tilix-nautilus util-linux-user zsh

```
**Error**
```
(nautilus:4551): Nautilus-Python-WARNING **: 17:10:04.226: g_module_open libpython failed: /usr/lib64/libpython3.7.so.1.0: cannot open shared object file: No such file or directory
ImportError: could not import gobject (error was: ImportError('/usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError'))

(nautilus:4551): Nautilus-Python-WARNING **: 17:10:04.282: pygobject initialization failed

(nautilus:4551): Nautilus-Python-WARNING **: 17:10:04.282: nautilus_python_init_python failed
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/open-tilix.py", line 15, in <module>
    from gi import require_version
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError

```

CC @bilelmoussaoui @kirbyfan64

**Comment by bilelmoussaoui** [comment]
Not a Tilix issue. Must be a pygobject issue I guess.

**Comment by alex285** [comment]
i guessed that's why i cc you and Ryan if you have a solution since you have both used SB. Ryan i think still has a SB

**Comment by kirbyfan64** [comment]
Based on some research, this is most definitely an issue with pygobject, maybe with how it was specifically built and/or integrated with the Silverblue tree.

**Comment by alex285** [comment]
I add it to SB Forum if someone there can help
https://discussion.fedoraproject.org/t/tilix-nautilus-plugin-doesnt-work/590

**Comment by dact221** [comment]
I have exactly the same issue even on normal Fedora.

**Comment by alex285** [comment]
> I have exactly the same issue even on normal Fedora.

i can verify. i also can verify that it was used to work in Fedora
