### ISSUE TITLE
[Fedora 29] open-tilix extension fails to load

### ISSUE THREAD

**Issue by sebastien** [gnunn1/tilix#1570]
I'm not sure if it's a tilix or Fedora bug, but here's what I get when starting Nautilus from the command-line:

```
nautilus -q; and nautilus ~/ 

(nautilus:9166): Nautilus-Python-WARNING **: 15:05:30.075: g_module_open libpython failed: /usr/lib64/libpython3.7.so.1.0: cannot open shared object file: No such file or directory
ImportError: could not import gobject (error was: ImportError('/usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError'))

(nautilus:9166): Nautilus-Python-WARNING **: 15:05:30.119: pygobject initialization failed

(nautilus:9166): Nautilus-Python-WARNING **: 15:05:30.119: nautilus_python_init_python failed
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/open-tilix.py", line 15, in <module>
    from gi import require_version
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/insync_plugin.py", line 19, in <module>
    from gi.repository import GObject
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError
```

There is, however, a `/usr/lib64/libpython3.7m.so` library available.

**Comment by sebp** [comment]
Should have been resolved upstream according to https://bugzilla.redhat.com/show_bug.cgi?id=1642927

**Comment by sebastien** [comment]
OK, thanks! I'll wait for the patch to land in F29 release, thanks for binding the upstream bug!
