### ISSUE TITLE
no option for 'open with tilix' in nautilus 

### ISSUE THREAD

**Issue by rudrab** [gnunn1/tilix#2117]
Hi,
With gnome 43 (fedora 37-beta-rc), there is no ''Open with Tilix" option anymore. 
Any way to implement it?

**Comment by eda2z** [comment]
I am getting the same behavior (error messages and no "Open with Tilix") in Arch. Gnome shell version 43.1. If I try nautilus --version (not sure if that is valid) I get
`
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/open-tilix.py", line 17, in <module>
    require_version('Nautilus', '3.0')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Nautilus is already loaded with version 4.0
GNOME nautilus 43.0

(org.gnome.Nautilus:21344): GLib-CRITICAL **: 14:30:17.662: g_hash_table_foreach: assertion 'hash_table != NULL' failed

`

**Comment by dantob** [comment]
```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/open-tilix.py", line 17, in <module>
    require_version('Nautilus', '3.0')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Nautilus is already loaded with version 4.0
```

After changing the required version to 4, it now fails with this

```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/open-tilix.py", line 40, in <module>
    Nautilus.LocationWidgetProvider):
  File "/usr/lib/python3.10/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Nautilus' object has no attribute 'LocationWidgetProvider'
```

and the migration docs say

`The Nautilus.LocationWidgetProvider was removed without replacement. If your script requires it, you can request a new model-based API for your specific use case on the Nautilus issue tracker`

**Comment by dantob** [comment]
https://github.com/gnunn1/tilix/pull/2115 works for me

**Comment by kalev** [comment]
I went ahead and backported #2115 to [tilix-1.9.5-6.fc37](https://bodhi.fedoraproject.org/updates/FEDORA-2022-085be0501a) for Fedora 37.

**Comment by rudrab** [comment]
> I went ahead and backported #2115 to [tilix-1.9.5-6.fc37](https://bodhi.fedoraproject.org/updates/FEDORA-2022-085be0501a) for Fedora 37.

Thanks a lot.

**Comment by sven-frotscher** [comment]
> I went ahead and backported #2115 to [tilix-1.9.5-6.fc37](https://bodhi.fedoraproject.org/updates/FEDORA-2022-085be0501a) for Fedora 37.

Arch backported it too: https://github.com/archlinux/svntogit-community/commit/ad16a37ac4323a2b2e2d22247f1b88a620031bde
