### ISSUE TITLE
Randomly appearing Segfaults

### ISSUE THREAD

**Issue by Manuel-Koenig** [gnunn1/tilix#832]
Hi,

in the last few days Terminix segfaulted a few times, which never happened before.
I think in all cases I was working with two split windows, running nvim in one window and compling stuff in the other window. This last crash happened while I was in the nvim window, here is a gdb backtrace:

```
Reading symbols from terminix...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/terminix 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffea282700 (LWP 10263)]
[New Thread 0x7fffe9a81700 (LWP 10264)]
[New Thread 0x7fffe8c56700 (LWP 10265)]

Thread 1 "terminix" received signal SIGSEGV, Segmentation fault.
0x00000000005d77ca in ?? ()
(gdb) bt
#0  0x00000000005d77ca in  ()
#1  0x00000000005d714e in  ()
#2  0x00007ffff62a7ed3 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff62a745a in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff62a7810 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff62a78bc in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff537b52d in g_application_run () at /usr/lib/libgio-2.0.so.0
#7  0x000000000057eecd in  ()
#8  0x00000000004ef908 in  ()
#9  0x0000000000a823ff in  ()
#10 0x0000000000a82344 in  ()
#11 0x0000000000a8226d in  ()
#12 0x000000000054ece5 in  ()
#13 0x00007ffff6bc3511 in __libc_start_main () at /usr/lib/libc.so.6
#14 0x00000000004055ea in  ()
(gdb) 
```

I'm using the ArchLinux Terminix version:

```
terminix --version
Versions
	Terminix version: 1.5.0
	VTE version: 0.46
	GTK Version: 3.22.10

Terminix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by gnunn1** [comment]
There was a problem in 1.5.0 with the timeout that was used to indicate the BELL visually. If you have the visual bell enabled in your profile, try disabling it or upgrade to 1.5.2 where it was fixed.

**Comment by Manuel-Koenig** [comment]
That's probably it! I just recently switched to using the visual bell. I'll upgrade and close the issue.
